### ISSUE TITLE
Gộp README.md và Rules.md

### ISSUE THREAD

**Issue by joulev** [vnma0/Hack2019COC#2]
Em nghĩ nên đưa hết nội dung của [Rules.md](/vnma0/Hack2019COC/blob/master/Rules.md) vào [README.md](/vnma0/Hack2019COC/blob/master/README.md) để phần chính (nội quy) của Hackathon có thể được nhìn thấy ngay khi mở repo. (Và làm cho file README thật sự yêu cầu người đọc phải *read me*.)

**Comment by enbugging** [comment]
- Bản thể lệ hackathon này chỉ là bản nháp, được đưa lên công khai để mọi người góp ý và sửa đổi. Bản chính thức sẽ được công khai theo hình thức khác. Do vậy, việc để phần này đập vào mắt người đọc gần như không cần thiết.
 - README theo định nghĩa, là một file miêu tả nội dung trong repository. Thực tế mà nói, nó chỉ miêu tả những cái có trong repo này, ko phải bản thân nội dung repo. Vì vậy nên mình mới đề nghị tách làm 2 file.

**Comment by dungwinux** [comment]
Ít nhất cũng nên refer trong readme là có những nội dung gì trong repo.
Ex:
- `Rules.md`: Thể lệ cuộc thi

**Comment by enbugging** [comment]
Done.

**Comment by joulev** [comment]
Điều này đã được thảo luận và đã có một số thay đổi trong README.md, do đó em sẽ close issue này.
